### ISSUE TITLE
Move Opstool to python 3

### ISSUE THREAD

**Issue by costimuraru** [adobe/ops-cli#1]
[Migrated]

Python 2 is EOL in 1 yr 5 months - as such, all of my team's development is being done in Python 3. Mixing Opstool into python 3 projects is a bit cumbersome and requires virtualenvs and other nastiness - maybe it's time to port opstool to python 3? FWIW I'd be willing to do a bunch of the legwork for this, just want to gauge interest before I undertake such a task.

**Comment by amuraru** [comment]
the python2 EOL is approaching. @costimuraru should we give this a try?

**Comment by murchgo** [comment]
@costimuraru any idea on timeline of this?
