### ISSUE TITLE
Terraform v0.12 - deprecated CLI option `-module-depth`

### ISSUE THREAD

**Issue by Symphony-AaronKulick** [adobe/ops-cli#31]
Terraform v0.12 disables `module-depth` option for all operations except graph (as of `0.v12-alpha3`): 
 https://github.com/hashicorp/terraform/commit/178ec8f7b42f1bbe5eb3c449da811d2872eacc6d#diff-aa88524f69c6514b7d5568e0b5e03bad

### Expected Behaviour

1. Install Python
1. `pip install https://github.com/adobe/ops-cli/releases/download/0.30/ops-0.30-py2-none-any.whl`
1. `brew install terraform` # CURRENT VERSION v0.12
1. `ops environment/path.yaml terraform plan`
1. Generate a valid plan file.

### Actual Behaviour

Terraform dumps usage.

### Reproduce Scenario (including but not limited to)

Have Terraform v0.12 installed.

#### Steps to Reproduce

1. Install Python
1. `pip install https://github.com/adobe/ops-cli/releases/download/0.30/ops-0.30-py2-none-any.whl`
1. `brew install terraform` # CURRENT VERSION v0.12
1. `git clone https://github.com/adobe/ops-cli.git`
1. `cd 
1. `ops environment/sample-cluster.yaml terraform plan`

1. Generate a valid plan file.

#### Platform and Version

MacOS 10.14.5
Terraform Version: v0.12.2 (or >v0.12-alpha3)
OPS-CLI Version: v0.30

#### Sample Code that illustrates the problem

Any valid operational config.

#### Logs taken while reproducing problem

```
cd ${HOME}/terraform && terraform get -update && terraform init && terraform refresh -input=false  -var 'cluster=aaron-kulick-dev'  -state=terraform.aaron-kulick-dev.tfstate && terraform plan -out=terraform.aaron-kulick-dev.plan -refresh=false -module-depth=1 -input=false  -var 'cluster=aaron-kulick-dev'  -state=terraform.aaron-kulick-dev.tfstate
```
N/A - c.f. CLI execution as debug output.

**Comment by costimuraru** [comment]
Thanks for the heads up @Symphony-AaronKulick 

I see module-depth is used in a few places in the terraform plugin:
https://github.com/adobe/ops-cli/blob/master/src/ops/cli/terraform.py#L222
https://github.com/adobe/ops-cli/blob/master/src/ops/cli/terraform.py#L272

@amuraru any concern with removing the flag? I see the following definition on the flag:

> -module-depth=n  Specifies the depth of modules to show in the output.	
> By default this is -1, which will expand all.

**Comment by amuraru** [comment]
+1 on removing that @costimuraru
