### ISSUE TITLE
Enable plugin caching when running terraform commands

### ISSUE THREAD

**Issue by amuraru** [adobe/ops-cli#66]
### Expected Behaviour
Enable TF_PLUGIN_CACHE_DIR in docker container to speed up tf commands.

e.g.
```
export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
mkdir -p $TF_PLUGIN_CACHE_DIR
```

### Actual Behaviour

Currently, when using ops-cli to drive EKS clusters there are multiple `tf` commands ran.
For each of this run, tf downloads aws tf provider slowing the overall command.

```
- Downloading plugin for provider "aws" (hashicorp/aws) 2.30.0...
```

@costimuraru do you see any issue in enabling this?

**Comment by costimuraru** [comment]
Nice! Wondering if we could the same when running locally. Perhaps a flag in the .opsconfig to enable this behavior?

**Comment by amuraru** [comment]
local as well, yes - it makes sense

**Comment by serban21** [comment]
There is one (potential) problem, the entire `.terraform` folder is deleted if `terraform.remove_local_cache` is enabled (see https://github.com/adobe/ops-cli/blob/master/src/ops/terraform/terraform_cmd_generator.py#L103). I added that for situations when you have mixed terraform backends (local and S3).

**Comment by amuraru** [comment]
@serban21 - you're talkling about local `.terraform` dir right? 
I was suggesting we have this `TF_PLUGIN_CACHE_DIR` set to user $HOME global and not one per cluster

**Comment by serban21** [comment]
@amuraru You are right, we just tested this locally on my laptop and it's working nice.
